### ISSUE TITLE
Not compatible with TypeScript

### ISSUE THREAD

**Issue by ajshres** [cht8687/react-hover#16]
I like your extension library but as per my research, type definition can not be created for your library.
Could you please separate Trigger and Hover from ReactHover definition and export as separate entity?

could you please export as `export { Trigger, Hover };` instead of [Change This](https://github.com/cht8687/react-hover/blob/master/src/ReactHover.js#L100-L101)

or any other viable solution

**Comment by cht8687** [comment]
@ddvkid @ttma1046 any insights for this?

**Comment by cht8687** [comment]
@ajshres 
Sorry for the late reply. 
The benefit of wrap the lib into `ReactHover` is that it won't have conflicts with other libraries in the project.
I am not really sure what other impacts it will bring if we export them separately.
What's the reason that type definition failed here? could you supply any insights so that we can tackle this together? 
cheers.

**Comment by Isaius** [comment]
Still not compatible with TS?

**Comment by cht8687** [comment]
https://github.com/cht8687/react-hover/blob/master/src/index.js#L2

Released in 2.0.0
